BiletifyUI/Areas/Admin/Controllers/OrderController.cs
using Biletify.Business.Abstract;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BiletifyUI.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin, Moderator")]
    [Area("Admin")]
    public class OrderController : Controller
    {
        private readonly IOrderService _orderManager;

        public OrderController(IOrderService orderManager)
        {
            _orderManager = orderManager;
        }

        public async Task<IActionResult> Index()
        {
            var orders = await _orderManager.GetAllOrderAsync();
            return View(orders);
        }
    }
}

BiletifyUI/Areas/Admin/Controllers/ProductController.cs
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using BiletifyUI.Areas.Admin.Helpers;
using System.Collections.Generic;
using System.Text;
using System.Text.Json;
using BiletifyUI.Extensions;
using Biletify.Business.Abstract;
using Biletify.Shared.Helpers.Abstract;
using Microsoft.AspNetCore.Authorization;
using Biletify.Business.Concrete;
using Biletify.Shared.Helpers.Concrete;
using Biletify.Shared.ResponseViewModels;
using Biletify.Shared.ViewModels;
using BiletifyUI.Helpers;



namespace BiletifyUI.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    [Area("Admin")]
    public class ProductController : Controller
    {
        private readonly IProductService _productManager;
        private readonly ICategoryService _categoryManager;
        private readonly IImageHelper _imageHelper;

        public ProductController(IProductService productManager, ICategoryService categoryManager, IImageHelper imageHelper)
        {
            _productManager = productManager;
            _categoryManager = categoryManager;
            _imageHelper = imageHelper;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index(bool id = false)
        {
            Response<List<ProductViewModel>> result = await _productManager.GetAllNonDeletedAsync(id);
            ViewBag.ShowDeleted = id;
            return View(result.Data);
        }


        public async Task<IActionResult> UpdateIsHome(int id)
        {
            var result = await _productManager.UpdateIsHomeAsync(id);
            return RedirectToAction("Index");
        }


        public async Task<IActionResult> UpdateIsActive(int id)
        {
            var result = await _productManager.UpdateIsActiveAsync(id);
            return RedirectToAction("Index");
        }


        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var categories = await _categoryManager.GetActiveCategories();
            AddProductViewModel model = new AddProductViewModel
            {
                Categories = categories.Data
            };
            return View(model);
        }


        [HttpPost]
        public async Task<IActionResult> Create(AddProductViewModel model, IFormFile image)
        {
            if (ModelState.IsValid && model.CategoryIds.Count > 0 && image != null)
            {
                model.ImageUrl = await _imageHelper.UploadImage(image, "products");
                model.Url = Jobs.GetUrl(model.Name);
                await _productManager.CreateAsync(model);
                return RedirectToAction("Index");
            }
            ViewBag.CategoryErrorMessage = model.CategoryIds.Count == 0 ? "Herhangi bir kategori seçmeden, ürün kaydı yapılamaz" : null;
            ViewBag.ImageErrorMessage = model.ImageUrl == null || model.ImageUrl == "" ? "Resim hatalı!" : null;
            var categories = await _categoryManager.GetActiveCategories();
            model.Categories = categories.Data;
            return View(model);
        }


        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var product = await _productManager.GetProductWithCategoriesAsync(id);
            ProductViewModel productViewModel = product.Data;
            var categories = await _categoryManager.GetActiveCategories();
            EditProductViewModel model = new EditProductViewModel
            {
                Id = productViewModel.Id,
                Name = productViewModel.Name,
                ImageUrl = productViewModel.ImageUrl,
                IsActive = productViewModel.IsActive,
                IsHome = productViewModel.IsHome,
                Price = productViewModel.Price,
                Properties = productViewModel.Properties,
                Url = productViewModel.Url,
                CategoryIds = productViewModel.CategoryList.Select(c => c.Id).ToList(),
                Categories = categories.Data,
            };
            return View(model);
        }


        [HttpPost]
        public async Task<IActionResult> Edit(EditProductViewModel model, IFormFile image)
        {
            if (ModelState.IsValid && model.CategoryIds.Count > 0)
            {
                if (image != null)
                {
                    model.ImageUrl = await _imageHelper.UploadImage(image, "products");
                }
                model.Url = Jobs.GetUrl(model.Name);
                await _productManager.UpdateAsync(model);
                return RedirectToAction("Index");
            }
            ViewBag.CategoryErrorMessage = model.CategoryIds.Count == 0 ? "Herhangi bir kategori seçmeden, ürün kaydı yapılamaz" : null;
            var categories = await _categoryManager.GetActiveCategories();
            model.Categories = categories.Data;
            return View(model);
        }


        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var product = await _productManager.GetByIdAsync(id);
            ProductViewModel productViewModel = product.Data;
            DeleteProductViewModel model = new DeleteProductViewModel
            {
                Id = productViewModel.Id,
                Name = productViewModel.Name,
                Price = productViewModel.Price,
                CreatedDate = productViewModel.CreatedDate,
                ModifiedDate = productViewModel.ModifiedDate,
                IsDeleted = productViewModel.IsDeleted,
                ImageUrl = productViewModel.ImageUrl
            };
            return View(model);
        }


        [HttpGet]
        public async Task<IActionResult> HardDelete(int id)
        {
            await _productManager.HardDeleteAsync(id);
            return RedirectToAction("Index");
        }


        [HttpGet]
        public async Task<IActionResult> SoftDelete(int id)
        {
            await _productManager.SoftDeleteAsync(id);
            var productViewModel = await _productManager.GetByIdAsync(id);
            return Redirect($"/Admin/Product/Index/{!productViewModel.Data.IsDeleted}");
        }
    }
}

BiletifyUI/Areas/Admin/Controllers/RoleController.cs
using Biletify.Entity.Concrete.Identity;
using Biletify.Shared.ViewModels.IdentityViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BiletifyUI.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    [Area("Admin")]
    public class RoleController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly RoleManager<Role> _roleManager;

        public RoleController(UserManager<User> userManager, RoleManager<Role> roleManager)
        {
            _userManager = userManager;
            _roleManager = roleManager;
        }

        public async Task<IActionResult> Index()
        {
            List<Role> roles = await _roleManager.Roles.ToListAsync();
            List<RoleViewModel> roleViewModels = roles.Select(r => new RoleViewModel
            {
                Id = r.Id,
                Name = r.Name,
                Description = r.Description
            }).ToList();
            return View(roleViewModels);
        }
    }
}

BiletifyUI/Controllers/UserController.cs
using Biletify.Business.Abstract;
using Biletify.Entity.Concrete.Identity;
using Biletify.Shared.ViewModels.IdentityViewModels;
using Microsoft.AspNetCore.Cors.Infrastructure;
using Microsoft.AspNetCore.Identity;

using Microsoft.AspNetCore.Mvc;
using System.Data;


namespace BiletifyUI.Controllers
{
    public class UserController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly RoleManager<Role> _roleManager;
        private readonly SignInManager<User> _signInManager;
        private readonly ICartService _cartManager;
        private readonly IOrderService _orderManager;

        public UserController(UserManager<User> userManager, RoleManager<Role> roleManager, SignInManager<User> signInManager, ICartService cartManager, IOrderService orderManager)
        {
            _userManager = userManager;
            _roleManager = roleManager;
            _signInManager = signInManager;
            _cartManager = cartManager;
            _orderManager = orderManager;
        }

        public async Task<IActionResult> Index()
        {
            var userId = _userManager.GetUserId(User);
            var orders = await _orderManager.GetAllOrderAsync(userId);
            return View(orders);
        }

        public IActionResult AccessDenied()
        {
            return View();
        }

        public async Task<IActionResult> Login(string returnUrl = null)
        {
            return View(new LoginViewModel { ReturnUrl = returnUrl });
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel loginViewModel)
        {
            if (ModelState.IsValid)
            {
                User user = await _userManager.FindByNameAsync(loginViewModel.UserName);
                if (user == null)
                {
                    ModelState.AddModelError("", "Kullanıcı adı bulunamadı");
                    return View(loginViewModel);
                }
                var result = await _signInManager.PasswordSignInAsync(user, loginViewModel.Password, false, false);
                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", "Parola hatalı");
                    return View(loginViewModel);
                }
                return Redirect(loginViewModel.ReturnUrl ?? "~/");
            }
            return View(loginViewModel);
        }

        public async Task<IActionResult> Logout()
        {
            await _signInManager.SignOutAsync();
            return Redirect("~/");
        }

        [HttpGet]
        public IActionResult SignUp()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> SignUp(SignUpViewModel signUpViewModel)
        {
            if (ModelState.IsValid)
            {
                User newUser = new User
                {
                    UserName = signUpViewModel.UserName,
                    Email = signUpViewModel.Email,
                    FirstName = signUpViewModel.FirstName,
                    LastName = signUpViewModel.LastName
                };
                var result = await _userManager.CreateAsync(newUser, signUpViewModel.Password);
                if(result.Succeeded)
                {
                    await _userManager.AddToRoleAsync(newUser, "Customer");
                    await _cartManager.InitializeCartAsync(newUser.Id);
                    return RedirectToAction("Login");
                }
            }
            return View(signUpViewModel);
        }

    }
}

BiletifyUI/Areas/Admin/Views/Shared/_DataTablesScriptsPartial.cshtml
<!-- DataTables  & Plugins -->
<script src="~/admin/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="~/admin/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
<script src="~/admin/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
<script src="~/admin/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
<script src="~/admin/plugins/datatables-buttons/js/dataTables.buttons.min.js"></script>
<script src="~/admin/plugins/datatables-buttons/js/buttons.bootstrap4.min.js"></script>
<script src="~/admin/plugins/jszip/jszip.min.js"></script>
<script src="~/admin/plugins/pdfmake/pdfmake.min.js"></script>
<script src="~/admin/plugins/pdfmake/vfs_fonts.js"></script>
<script src="~/admin/plugins/datatables-buttons/js/buttons.html5.min.js"></script>
<script src="~/admin/plugins/datatables-buttons/js/buttons.print.min.js"></script>

<script>
$(function () {
    $.ajax({
        url: "//cdn.datatables.net/plug-ins/1.10.25/i18n/Turkish.json",
        dataType: 'json',
        success: function (data) {
            $("#myDataTable").DataTable({
                "responsive": true,
                "lengthChange": false,
                "autoWidth": false,
                "buttons": ["copy", "excel", "pdf", "print"],
                "language": data
            }).buttons().container().appendTo('#myDataTable_wrapper .col-md-6:eq(0)');
        }
    });
});
</script>

BiletifyUI/Areas/Admin/Views/Shared/_DataTablesStylesPartial.cshtml
<!-- DataTables -->
<link rel="stylesheet" href="~/admin/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
<link rel="stylesheet" href="~/admin/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
<link rel="stylesheet" href="~/admin/plugins/datatables-buttons/css/buttons.bootstrap4.min.css">

BiletifyUI/Areas/Admin/Views/Shared/_FooterPartial.cshtml
 <!--Footer-->
<footer class="main-footer">
    <strong>Telif Hakkı &copy; 2024 <a class="text-success" target="_blank" href="https://www.linkedin.com/in/mert-aydo%C4%9Fdu-b3a197250/">Mert Aydoğdu</a>.</strong>
    Tüm hakları saklıdır.
    <div class="float-right d-none d-sm-inline-block">
        <b>Versiyon</b> 1.0.0
    </div>
</footer>

BiletifyUI/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="tr">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Biletify | Dashboard</title>

    @await RenderSectionAsync("Styles", false)

    @await Html.PartialAsync("_StylesPartial")

</head>

<body class="hold-transition sidebar-mini layout-fixed">
  <div class="wrapper">

    @await Html.PartialAsync("_PreloaderPartial")

    @await Html.PartialAsync("_NavbarPartial")
    
    @await Html.PartialAsync("_MainSideBarContainerPartial")

    @RenderBody()
    @await Html.PartialAsync("_FooterPartial")
    
    
  </div>
  <!-- ./wrapper -->

  @await Html.PartialAsync("_ScriptsPartial")
  @await RenderSectionAsync("Scripts", false)
</body>

</html>

BiletifyUI/Areas/Admin/Views/Shared/_MainSideBarContainerPartial.cshtml
<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-success elevation-4">
    <!-- Brand Logo -->
    <a asp-area="Admin" asp-controller="Home" asp-action="Index"  class="brand-link">
        <img src="~/admin/dist/img/tify-white.png" alt="Biletify Logo" class="brand-image img-circle elevation-3"
             style="opacity: .8;">
        <span class="brand-text font-weight-light">Biletify Panel</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
        @await Component.InvokeAsync("SideBarUser")


        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">

                <!--ürünler menüsü-->
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        &nbsp;&nbsp;<i class="fa-solid fa-ticket"></i>&nbsp;
                        <p>
                            Ürünler
                            <i class="fas fa-angle-left right"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a asp-area="Admin" asp-controller="Product" asp-action="Index" asp-route-id="false" class="nav-link">
                                &nbsp;&nbsp;<i class="fa-solid fa-list"></i>&nbsp;
                                <p>Ürün Listesi</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-area="Admin" asp-controller="Product" asp-action="Create" class="nav-link">
                                &nbsp;&nbsp;<i class="fa-solid fa-plus"></i>&nbsp;
                                <p>Ürün Ekle</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-area="Admin" asp-controller="Product" asp-action="Index" asp-route-id="true" class="nav-link">
                                &nbsp;&nbsp;<i class="fa-solid fa-trash"></i>&nbsp;
                                <p>Çöp Kutusu</p>
                            </a>
                        </li>
                    </ul>
                </li>

                <!--Kategoriler menüsü-->
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-chart-pie"></i>
                        <p>
                            Kategoriler
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a asp-area="Admin" asp-controller="Category" asp-action="Index" class="nav-link">
                                &nbsp;&nbsp;<i class="fa-solid fa-list"></i></i>&nbsp;
                                <p>Kategori Listesi</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-area="Admin" asp-controller="Category" asp-action="Create" class="nav-link">
                                &nbsp;&nbsp;<i class="fa-solid fa-plus"></i>&nbsp;
                                <p>Kategori Ekle</p>
                            </a>
                        </li>
                    </ul>
                </li>

                <!--Kullanıcılar menüsü-->
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        &nbsp;&nbsp;<i class="fa-solid fa-users"></i>&nbsp;
                        <p>
                            Kullanıcılar
                            <i class="fas fa-angle-left right"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a asp-area="Admin" asp-controller="User" asp-action="Create" class="nav-link">
                                &nbsp;&nbsp;<i class="fa-solid fa-user-plus"></i>&nbsp;
                                <p>Yeni Kullanıcı</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-area="Admin" asp-controller="User" asp-action="Index" class="nav-link">
                                &nbsp;&nbsp;<i class="fa-solid fa-user-tie"></i>&nbsp;
                                <p>Tüm Kullanıcılar</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-area="Admin" asp-controller="Role" asp-action="Index" class="nav-link">
                                &nbsp;&nbsp;<i class="fa-solid fa-user-tag"></i>&nbsp;
                                <p>Rol Listesi</p>
                            </a>
                        </li>
                    </ul>
                </li>

                <!--Siparişler menüsü-->
                <li class="nav-item">
                    <a asp-area="Admin" asp-controller="Order" asp-action="Index" class="nav-link">
                        &nbsp;&nbsp;<i class="fa-solid fa-cart-arrow-down"></i>&nbsp;
                        <p>Siparişler</p>
                    </a>
                </li>
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>

BiletifyUI/Areas/Admin/Views/Shared/_NavbarPartial.cshtml
<!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block bg-success">
            <a target="_blank" asp-area="Index" asp-controller="Home" asp-action="Index" class="nav-link text-dark">Siteye Geç</a>
        </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
        <!-- Navbar Search -->
        <li class="nav-item">
            <a class="nav-link" data-widget="navbar-search" href="#" role="button">
                <i class="fas fa-search"></i>
            </a>
            <div class="navbar-search-block">
                <form class="form-inline">
                    <div class="input-group input-group-sm">
                        <input class="form-control form-control-navbar" type="search" placeholder="Arayın" aria-label="Search">
                        <div class="input-group-append">
                            <button class="btn btn-navbar" type="submit">
                                <i class="fas fa-search"></i>
                            </button>
                            <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                                <i class="fas fa-times"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </li>

       @await Component.InvokeAsync("NavbarMessages")

       @await Component.InvokeAsync("NavbarNotifications")
        <!--Fullscreen Menu-->
        <li class="nav-item">
            <a class="nav-link" data-widget="fullscreen" href="#" role="button">
                <i class="fas fa-expand-arrows-alt"></i>
            </a>
        </li>
    </ul>
</nav>
<!-- /.navbar -->

BiletifyUI/Areas/Admin/Views/Shared/_PreloaderPartial.cshtml
  <!-- Preloader -->
<div class="preloader flex-column justify-content-center align-items-center">
    <img class="animation__shake ml-1" src="~/admin/dist/img/tify-logo.png" alt="adminTicketLogo" height="60" width="60">
</div>

BiletifyUI/Areas/Admin/Views/Shared/_ScriptsPartial.cshtml
<!-- jQuery -->
<script src="~/admin/plugins/jquery/jquery.min.js"></script>


<!-- Bootstrap 4 -->
<script src="~/admin/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>


<!-- Summernote -->
<script src="~/admin/plugins/summernote/summernote-bs4.min.js"></script>

<!-- overlayScrollbars -->
<script src="~/admin/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>

<!-- AdminLTE App -->
<script src="~/admin/dist/js/adminlte.js"></script>

BiletifyUI/Areas/Admin/Views/Shared/_StylesPartial.cshtml
  <!-- Google Font: Source Sans Pro -->
<link rel="stylesheet"
      href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
<!-- Font Awesome -->
<link rel="stylesheet" href="~/admin/plugins/fontawesome-free/css/all.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" />

<!-- Theme style -->
<link rel="stylesheet" href="~/admin/dist/css/adminlte.min.css">
<!-- overlayScrollbars -->
<link rel="stylesheet" href="~/admin/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
<!-- summernote -->
<link rel="stylesheet" href="~/admin/plugins/summernote/summernote-bs4.min.css">